import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file is generated by the FlutterFire CLI.
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:hapii/screens/homescreen.dart';
import 'package:hapii/screens/loginscreen.dart';
import 'package:hapii/screens/profilescreen.dart';
import 'package:hapii/services/auth.dart';
import 'package:hapii/widgets/bottomNavBar.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using the generated options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (context) => GoogleSignInProvider(),
      child: const MaterialApp(
        debugShowCheckedModeBanner: false,
        home: NavScreen(),
      ),
    );
  }
}

class NavScreen extends StatelessWidget {
  const NavScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: StreamBuilder(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (context, snapshot) {
          return snapshot.hasData
              ? BottomNavBar(false, const Text(""))
              : const LoginScreen();
        },
      ),
    );
  }
}